{pkgs, ...}: {
  home.packages = with pkgs; [
    audacity
    blender
    gimp
    inkscape
    krita
    kdenlive
    onlyoffice-bin
    vlc
    mpv
    xournalpp
    eclipses.eclipse-java
    vscodium.fhs
    ungoogled-chromium
    alacritty
    foot
    godot
    wireshark
    obs-studio
    ferdium
    nextcloud-client
    signal-desktop
    monero-gui
    qbittorrent
    # tor-browser-bundle-bin
    firefox
    librewolf
    xorg.xeyes
    airshipper
    minecraft
    moonlight-qt
    superTuxKart
  ];

  home.persistence."/nix/state/home/mbund".directories = [
    ".local/share/airshipper"
    ".minecraft"
    ".mozilla"
    ".librewolf"
    ".config/obs-studio"
    ".config/Signal"
    ".config/supertuxkart"
    ".config/VSCodium"
    ".vscode-oss"
    ".config/chromium"
    ".config/godot"
    ".local/share/godot"
    ".config/Ferdium"
    ".config/alacritty"
    ".config/Nextcloud"
    ".config/inkscape"
    ".config/krita"
    ".config/xournalpp"
    ".config/vlc"
    ".config/mpv"
    ".local/share/onlyoffice"
  ];
}
