#!/usr/bin/env sh

init="$(($(cat /sys/class/net/[ew]*/statistics/rx_bytes | paste -sd '+')))"

printf "Recording bandwidth. Press enter to stop."

read -r lol

fin="$(($(cat /sys/class/net/[ew]*/statistics/rx_bytes | paste -sd '+')))"

notify-send $(numfmt --to=iec $(($fin-$init))) "of bandwidth used." 
